Repository icaodle/icaodle, pull requests merged in 2022-04, with the labels that each got.

#67 Temp Removed Hard Mode
  script.js
Labels: exclude

#70 Added click-outside Feature
  script.js
Labels: feature

#68 Updated Tutorial Content
  script.js
Labels: exclude

#69 Dark Mode Improvements
  style.css
Labels: enhancement

#71 Fixed Hint Cursor Bug
  script.js
Labels: bug

#72 Tutorial Pop-Up Complete
  script.js
Labels: enhancement

#74 Reworked Commented Material
  script.js
Labels: exclude

#73 New Airport Button
  index.html
  script.js
  style.css
Labels: enhancement

#76 Removed old JS version of CSS transition
  script.js
Labels: cleanup

#78 Revert "Removed Old JS Version of CSS Transition"
  script.js
Labels: exclude

#79 Revert "Revert "Removed Old JS Version of CSS Transition""
  script.js
Labels: exclude

#80 Exam > Test
  README.md
Labels: documentation

#81 Updated Version Number
  script.js
Labels: enhancement, exclude

#84 Fixed: Clear Row Button Frozen
  script.js
Labels: bug

#85 Fixed Cursor Styling
  style.css
Labels: bug

#87 Update feature-request.md
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: documentation

#88 Create .htaccess
  .htaccess
Labels: developer

#89 Update to Intl. Mode in Settings
  script.js
Labels: enhancement, exclude

#83 Max Sizes
  script.js
Labels: enhancement

#90 Added Tutorial Scrolling
  style.css
Labels: enhancement

#92 International Mode Defaults to "On"
  .replit
  script.js
Labels: exclude

#93 Site Deployment
  .replit
  script.js
Labels: deployment

#94 Improved Version Workflow
  script.js
Labels: developer

#95 Intl. Mode Changes Code if no Previous Guesses are Present
  script.js
Labels: enhancement

#97 Added Container Margins
  style.css
Labels: enhancement

#96 Fixed Typing from Settings/Tutorial
  script.js
Labels: bug

#98 Green Bar for Last Guess
  script.js
Labels: enhancement

#99 Deployment
  script.js
  style.css
Labels: deployment

#100 Credited Icons
  index.html
Labels: developer

#101 Added Font Awesome Credit
  README.md
Labels: developer

#102 Formatting and Added Semicolons
  .prettierignore
  .prettierrc
  script.js
  style.css
Labels: cleanup
