Repository icaodle/icaodle, pull requests merged in 2022-10, with the labels that each got.

#109 Objectify
  .prettierignore
  .prettierrc
  index.html
  script.js
  scripts/airport_handler.js
  scripts/app.js
  scripts/dev.js
  scripts/end_screen.js
  scripts/feedback_handler.js
  scripts/game.js
  scripts/hints.js
  scripts/keyboard.js
  scripts/local_storage_manager.js
  scripts/script.js
  scripts/settings.js
  scripts/tutorial.js
Labels: cleanup

#112 Missing Hints Differentiation
  scripts/hints.js
Labels: enhancement

#111 Update Version Number
  scripts/app.js
Labels: developer

#113 Site Deployment v1.1.0
  .prettierignore
  .prettierrc
  .replit
  index.html
  script.js
  scripts/airport_handler.js
  scripts/app.js
  scripts/dev.js
  scripts/end_screen.js
  scripts/feedback_handler.js
  scripts/game.js
  scripts/hints.js
  scripts/keyboard.js
  scripts/local_storage_manager.js
  scripts/script.js
  scripts/settings.js
  scripts/tutorial.js
  style.css
Labels: deployment

#115 Settings Hotfix
  scripts/game.js
  scripts/settings.js
Labels: bug

#114 Update Version Number
  scripts/app.js
Labels: developer

#116 Site Deployment v1.1.1
  scripts/app.js
  scripts/game.js
  scripts/settings.js
Labels: deployment
