Repository icaodle/icaodle, pull requests merged in 2022-05, with the labels that each got.

#103 Refactor Feedback Function
  script.js
Labels: cleanup

#104 Site Deployment
  .prettierignore
  .prettierrc
  README.md
  index.html
  script.js
  style.css
Labels: deployment

#105 Refactor CSS
  .replit
  script.js
  style.css
Labels: cleanup

#108 More Codes
  script.js
Labels: enhancement
